baseurl: https://mooody.me/
languageCode: en-us
theme: hugo-theme-stack
paginate: 8
title: Moody's Front Page
hasCJKLanguage: true

staticDir:
    - static

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /favicon.ico

    footer:
        since: 2021
        customText: Mooooooooooooooooooooody

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: ❤️
        subtitle: What's the breaking news?
        avatar:
            local: true
            src: avatar.png

    article:
        math: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: utterances

        utterances:
            repo: moodyhunter/BlogComments
            issueTerm: pathname
            label: comments

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: 0-home
          weight: -100
          name: Home
          url: /
          params:
              icon: home
              newTab: false

        - name: ─────────────────
          weight: 100
          url: "#"

        - identifier: archrv-mirror
          weight: 105
          name: ArchRV Mirror
          url: https://archrv.mooody.me
          params:
              icon: download

        - identifier: grafana
          weight: 110
          name: Grafana
          url: https://g.mooody.me
          params:
              icon: db
              newTab: true

        - identifier: dashboard
          weight: 120
          name: MoodyAPI
          url: https://dash.mooody.me
          params:
              icon: settings
              newTab: true

        - identifier: gitea
          weight: 130
          name: Peronal Git
          url: https://git.mooody.me
          params:
              icon: git
              newTab: true

    social:
        - identifier: github
          weight: 110
          name: GitHub
          url: https://github.com/moodyhunter
          params:
              icon: brand-github

        - identifier: nextcloud
          weight: 120
          name: NextCloud
          url: https://nextcloud.mooody.me
          params:
              icon: cloud
              newTab: true

        - identifier: mailme
          weight: 140
          name: MailMe
          url: mailto://mooodyhunter@outlook.com
          params:
              icon: at
              newTab: true

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
